_wandb:
    value:
        cli_version: 0.26.1
        e:
            u2icgwouiu6h3zofbl4y67gzyntghxum:
                args:
                    - --wandb-project
                    - tla_bench_test
                codePath: src/evaluate_ground_truth.py
                codePathLocal: src/evaluate_ground_truth.py
                cpu_count: 56
                cpu_count_logical: 112
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "2009044758528"
                        used: "1754033606656"
                email: marslan@luc.edu
                executable: /usr/bin/python
                git:
                    commit: cefc029b8ac746c3cf1f3970d913970656d67803
                    remote: https://github.com/LUC-AI4FM/tla_benchmark.git
                gpu: Quadro RTX 8000
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "51539607552"
                      name: Quadro RTX 8000
                      uuid: GPU-5b47ea45-fff4-f214-b91f-9a8d6d052064
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "51539607552"
                      name: Quadro RTX 8000
                      uuid: GPU-f086a1ee-4a51-6b87-f822-d348bfd99b39
                host: aisec102
                memory:
                    total: "540638564352"
                os: Linux-6.8.0-106-generic-x86_64-with-glibc2.35
                program: /home/arslanbisharat/Documents/AI4FM/tla bench dashboard/src/evaluate_ground_truth.py
                python: CPython 3.10.12
                root: /home/arslanbisharat/Documents/AI4FM/tla bench dashboard
                startedAt: "2026-04-30T19:31:38.738262Z"
                writerId: u2icgwouiu6h3zofbl4y67gzyntghxum
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.12
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
model_id:
    value: ground_truth
