_wandb:
    value:
        cli_version: 0.26.1
        e:
            8p0injnjig7fps8znws3uzy09rh3com3:
                args:
                    - --model
                    - claude-haiku-4-5
                    - --limit
                    - "1"
                    - --api-key
                    - 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
                codePath: src/runner.py
                codePathLocal: src/runner.py
                cpu_count: 56
                cpu_count_logical: 112
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "2009044758528"
                        used: "1754006007808"
                email: marslan@luc.edu
                executable: /usr/bin/python
                git:
                    commit: cefc029b8ac746c3cf1f3970d913970656d67803
                    remote: https://github.com/LUC-AI4FM/tla_benchmark.git
                gpu: Quadro RTX 8000
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "51539607552"
                      name: Quadro RTX 8000
                      uuid: GPU-5b47ea45-fff4-f214-b91f-9a8d6d052064
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "51539607552"
                      name: Quadro RTX 8000
                      uuid: GPU-f086a1ee-4a51-6b87-f822-d348bfd99b39
                host: aisec102
                memory:
                    total: "540638564352"
                os: Linux-6.8.0-106-generic-x86_64-with-glibc2.35
                program: /home/arslanbisharat/Documents/AI4FM/tla bench dashboard/src/runner.py
                python: CPython 3.10.12
                root: /home/arslanbisharat/Documents/AI4FM/tla bench dashboard
                startedAt: "2026-04-30T19:54:20.142143Z"
                writerId: 8p0injnjig7fps8znws3uzy09rh3com3
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 2
                - 13
                - 16
                - 61
                - 62
            "4": 3.10.12
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
backend:
    value: anthropic
conditions:
    value:
        - nlp_to_tla
        - v2_to_tla
        - v3_to_tla
model_id:
    value: claude-haiku-4-5
model_name:
    value: claude-haiku-4-5
num_specs:
    value: 1
temperature:
    value: 0
